services:
  - type: web
    name: MORSTRIXBOT
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: WEBHOOK_HOST
        fromService:
          name: MORSTRIXBOT
          type: web
          property: url
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_SAFE_BROWSING_API_KEY
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: true