services:
  - type: web
    name: MORSTRIXBOT
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      RENDER: "true"
      TELEGRAM_BOT_TOKEN: "YOUR_BOT_TOKEN"
    autoDeploy: true
    healthCheckPath: /health