# render.yaml
services:
  - type: web
    name: MORSTRIXBOT
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.13"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      RENDER: "true"
      TELEGRAM_BOT_TOKEN: "YOUR_TOKEN"
    autoDeploy: true
    # healthCheckPath: видалено — не потрібно для polling